# Generated by Django 4.1.3 on 2022-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
